### ISSUE TITLE
Attribute code

### ISSUE THREAD

**Issue by sarabveer** [phtyson/calendar-mod#1]
Hello,

This is a very nice project. I have one request, could you please attribute your code as it has been taken from: https://github.com/sarabveer/calendrica-js/tree/master/src.

Also this code might not be compatible with the GPL license, as the functions and algorithms are taken from the book Calendrical Calculations. Please see the following: https://github.com/sarabveer/calendrica-js/blob/master/LICENSE.

Thanks!

**Comment by phtyson** [comment]
Thank you. I apologize for not properly attributing your work (for which I am very grateful!). I hope my latest commits are satisfactory.

I don't understand open-source licenses very well, but I agree the GPL was probably not compatible with the calendrica license. I changed to the Mozilla Public License for my code, and added the Calendrica 4.0 license in the calendrica directory.
